[package]
name = "social-chat-rust-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.0"
env_logger = "0.9.0"
sled = "0.34.7"
serde = "1.0.152"
once_cell = "1.17.1"